### ISSUE TITLE
Can I access windows unique element with AutomationInd?

### ISSUE THREAD

**Issue by baramofme** [simonmdsn/inputter#1]
I think the inputter can access the windows app elements by AutomationId. because win32 library is behind it.

 AutomationId is a unique identifier for an element in a Windows application and can be used to access it through automation tools. 

Here's an example of how to get the text from the Windows Calculator app's calculator result using its unique AutomationId in Robot Framework IDE:

![image](https://user-images.githubusercontent.com/44565599/219055460-21b53fe2-20b1-4db4-8e04-2d8d03caf93f.png)

but, I don't know how the inputter interacts with the element's automation Id.

**Comment by simonmdsn** [comment]
I could not find anything about AutomationId in the win32 library, could you point me in the right direction?
There is something called the GetClassName, which can retrieve some information about what is in the window.

I did not know this was possible but it elevates the degree of automation possible programmatically.

**Comment by baramofme** [comment]
@simonmdsn Oh. It's my mistake. 

[System.Windows.Automation](https://learn.microsoft.com/ko-kr/dotnet/api/system.windows.automation?view=windowsdesktop-7.0) is available .net browser api, but win32. sorry.

But I found another approach. using winAppdriver.

There's javascript libarary using winAppdriver.

https://www.npmjs.com/package/windows-app

```
import windowsApp from 'windows-app';

const {select, close} = await windowsApp('Microsoft.WindowsCalculator_8wekyb3d8bbwe!App'); // Calculator app

await select.name_('One').click();
await select.name_('Plus').click();
await select.name_('Two').click();
await select.name_('Equals').click();
const result = Number((await select.accessibilityId('CalculatorResults')).getText().replace('Display is', ''));

console.log(`The result of 1 + 2 is ${result}`);
//=> 'The result of 1 + 2 is 3'

await close();
```

[How To Automate Desktops Apps Using WinAppDriver](https://www.lambdatest.com/blog/how-to-automate-desktops-apps-using-winappdriver/#d)
